language: objective-c
osx_image: xcode10.2
install: true
branches:
  only:
    - master
    # Credit: @Omnikron13, https://github.com/mojombo/semver/issues/32
    - /^(\d+\.\d+\.\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
    - /^hotfix-(\d+\.\d+\.\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage/Build

jobs:
  include:
    - osx_image: xcode10.2
      script:
        - XCODE_SCHEME=FlexibleDiff-macOS
          XCODE_SDK=macosx
          XCODE_ACTION="build test"
          XCODE_DESTINATION="arch=x86_64"
          script/build
        - XCODE_SCHEME=FlexibleDiff-iOS
          XCODE_SDK=iphonesimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
          script/build
        - XCODE_SCHEME=FlexibleDiff-tvOS
          XCODE_SDK=appletvsimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV"
          script/build
    - script:
        - pod repo update --silent
        - pod lib lint FlexibleDiff.podspec --use-libraries
      env:
        - JOB=PODSPEC
    - stage: carthage
      script: carthage build --cache-builds --no-skip-current
